#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using LALR.CC.LexicalGrammar;

namespace DotCC;

/// <summary>Generated-output templating: the program/library C# shells (entry-point
/// wiring, Cond.B, runtime splice) and the paired csproj. One concern of
/// <see cref="Compiler"/> — entry points live in the main file.</summary>
public static partial class Compiler
{
    /// <summary>
    /// Build the csproj scaffold paired with the non-file-based shell from
    /// <see cref="EmitCSharp"/>. The frontend exe writes both into the output
    /// dir for the default csproj/build modes. When <paramref name="libraryMode"/>
    /// is true, configures <c>NativeLib=Shared</c> + <c>PublishAot=true</c>
    /// so <c>dotnet publish</c> produces a C-callable native shared library
    /// (<c>.dll</c> / <c>.so</c> / <c>.dylib</c>). <paramref name="managedLibrary"/> (with
    /// <paramref name="libraryMode"/>) is <c>-fassembly</c>: a plain class library, the managed
    /// library other dotcc programs reference, with no NativeAOT settings.
    /// <paramref name="projectReferences"/> are the projects of the managed libraries the
    /// program links (<see cref="ManagedLibraryManifests"/>), as paths relative to this one's
    /// directory: <c>dotnet build</c> builds them first and copies them beside the program.
    /// </summary>
    public static string BuildGeneratedCsproj(
        bool libraryMode = false, string assemblyName = "dotcc-out", IReadOnlyList<string>? staticArchives = null,
        bool managedLibrary = false, IReadOnlyList<string>? projectReferences = null)
    {
        var referenceItems = projectReferences is { Count: > 0 } projects
            ? "  <ItemGroup>\n"
              + string.Concat(projects.Select(p => $"    <ProjectReference Include=\"{p.Replace('\\', '/')}\" />\n"))
              + "  </ItemGroup>\n"
            : "";
        if (libraryMode && managedLibrary)
        {
            return $"""
                <Project Sdk="Microsoft.NET.Sdk">
                  <!-- Generated by dotcc (managed library, -shared -fassembly). -->
                  <PropertyGroup>
                    <OutputType>Library</OutputType>
                    <TargetFramework>net10.0</TargetFramework>
                    <RootNamespace>DotCCGenerated</RootNamespace>
                    <AssemblyName>{assemblyName}</AssemblyName>
                    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
                    <Nullable>disable</Nullable>
                  </PropertyGroup>
                {referenceItems}</Project>
                """;
        }
        // Static archives (.a/.lib): link them into the NativeAOT image. <DirectPInvoke>
        // tells ILC to resolve the [DllImport] stubs statically; <NativeLibrary> hands
        // the archive paths to the native linker. Forces PublishAot (static linking is
        // a publish-only operation — there's no CoreCLR static-link step). Empty when
        // no archive inputs were given.
        var staticItems = "";
        if (staticArchives is { Count: > 0 })
        {
            var sb = new StringBuilder();
            sb.Append("  <PropertyGroup>\n    <PublishAot>true</PublishAot>\n  </PropertyGroup>\n");
            sb.Append("  <ItemGroup>\n");
            foreach (var name in staticArchives.Select(StaticArchiveDllName).Distinct(StringComparer.Ordinal))
            {
                sb.Append($"    <DirectPInvoke Include=\"{name}\" />\n");
            }
            foreach (var path in staticArchives)
            {
                sb.Append($"    <NativeLibrary Include=\"{path.Replace('\\', '/')}\" />\n");
            }
            sb.Append("  </ItemGroup>\n");
            staticItems = sb.ToString();
        }

        if (libraryMode)
        {
            return $"""
                <Project Sdk="Microsoft.NET.Sdk">
                  <!-- Generated by dotcc (library mode, -shared). -->
                  <PropertyGroup>
                    <OutputType>Library</OutputType>
                    <TargetFramework>net10.0</TargetFramework>
                    <RootNamespace>DotCCGenerated</RootNamespace>
                    <AssemblyName>{assemblyName}</AssemblyName>
                    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
                    <Nullable>disable</Nullable>
                    <!-- NativeAOT shared-library knobs. Producing the actual
                         .so/.dll/.dylib requires `dotnet publish`. -->
                    <PublishAot>true</PublishAot>
                    <NativeLib>Shared</NativeLib>
                    <IsTrimmable>true</IsTrimmable>
                  </PropertyGroup>
                {staticItems}</Project>
                """;
        }
        return $"""
            <Project Sdk="Microsoft.NET.Sdk">
              <!-- Generated by dotcc. -->
              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net10.0</TargetFramework>
                <RootNamespace>DotCCGenerated</RootNamespace>
                <AssemblyName>{assemblyName}</AssemblyName>
                <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
                <Nullable>disable</Nullable>
                <!-- The Windows manifest dotcc writes beside this project (long paths). -->
                <ApplicationManifest Condition="Exists('{GeneratedAppManifestFile}')">{GeneratedAppManifestFile}</ApplicationManifest>
              </PropertyGroup>
            {staticItems}{referenceItems}</Project>
            """;
    }

    /// <summary>The file name of <see cref="GeneratedAppManifest"/> beside a generated
    /// executable's project, which <see cref="BuildGeneratedCsproj"/> references when it
    /// is present.</summary>
    public const string GeneratedAppManifestFile = "app.manifest";

    /// <summary>
    /// The Windows application manifest for a generated executable. A process is held
    /// to MAX_PATH (260 characters) wherever Windows enforces it, such as the current
    /// directory (C's <c>chdir</c> into a deep directory fails, and so does a relative
    /// open there), unless its manifest declares <c>longPathAware</c> and the machine
    /// enables long paths. A NativeAOT executable carries no manifest of its own, and
    /// the JIT apphost's does not declare it, so dotcc supplies one. Only Windows reads
    /// it; elsewhere it is inert.
    /// </summary>
    public const string GeneratedAppManifest = """
        <?xml version="1.0" encoding="utf-8"?>
        <!-- Generated by dotcc: long-path aware, see Compiler.GeneratedAppManifest. -->
        <assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
          <assemblyIdentity version="1.0.0.0" name="dotcc.generated.app"/>
          <application xmlns="urn:schemas-microsoft-com:asm.v3">
            <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
              <ws2:longPathAware>true</ws2:longPathAware>
            </windowsSettings>
          </application>
        </assembly>
        """;

    /// <summary>Generate the <c>dotcc zig test</c> entry-point body: run each lowered test
    /// (<c>__zigtest_N</c>, an <c>anyerror!void</c> method surfaced by <c>using static DotCcProgram;</c>)
    /// in source order, printing <c>OK</c>/<c>FAIL</c> per test plus a summary, and returning 0 iff all
    /// pass. A test FAILS when it returns an error (<c>ErrUnion.IsErr</c> — a propagated <c>try</c> or an
    /// explicit <c>return error.X</c>) OR throws (a panic / <c>unreachable</c> / runtime fault); both are
    /// caught so one failing test can't abort the run. Output is dotcc's own shape — real <c>zig test</c>
    /// output is non-deterministic (timing), so it is deliberately NOT byte-matched.</summary>
    private static string BuildTestEntry(IReadOnlyList<(string Name, string FnName)> tests)
    {
        var sb = new System.Text.StringBuilder();
        sb.Append("int __passed = 0, __failed = 0;\n");
        foreach (var (name, fn) in tests)
        {
            // Escape the display name for a C# string literal in the emitted runner.
            var lit = name.Replace("\\", "\\\\").Replace("\"", "\\\"");
            sb.Append($"            Console.Out.Write(\"test \\\"{lit}\\\" ... \");\n");
            sb.Append("            try\n");
            sb.Append("            {\n");
            sb.Append($"                var __r = {fn}();\n");
            sb.Append("                if (__r.IsErr) { Console.Out.WriteLine(\"FAIL (error \" + __r.Code + \")\"); __failed++; }\n");
            sb.Append("                else { Console.Out.WriteLine(\"OK\"); __passed++; }\n");
            sb.Append("            }\n");
            sb.Append("            catch (Exception __e) { Console.Out.WriteLine(\"FAIL (\" + __e.GetType().Name + \")\"); __failed++; }\n");
        }
        sb.Append("            Console.Out.WriteLine(__failed == 0\n");
        sb.Append("                ? \"All \" + __passed + \" test(s) passed.\"\n");
        sb.Append($"                : __failed + \" of {tests.Count} test(s) failed, \" + __passed + \" passed.\");\n");
        sb.Append("            return __failed == 0 ? 0 : 1;");
        return sb.ToString();
    }

    /// <summary>The most user functions one generated class holds. The CLR caps a type at
    /// 65535 methods (past it the program fails to load: "contains more methods than the
    /// current implementation allows"), and a function's local functions add to its class, so a
    /// large program (CPython: some 70k functions, most of them each unit's own copies of header
    /// <c>static inline</c> functions) is spread over several classes, which <c>using static</c>
    /// surfaces alike.</summary>
    internal const int FunctionsPerClass = 8192;

    /// <summary>The user functions as the static classes that hold them: <c>DotCcProgram</c>, and past
    /// <see cref="FunctionsPerClass"/> functions <c>DotCcProgram2</c>, <c>DotCcProgram3</c>, …, each method made
    /// <c>internal</c> so <c>using static</c> surfaces it. Returns the class names and their source.</summary>
    private static (string[] Names, string Source) ProgramClasses(IReadOnlyList<string> emittedFns)
    {
        var fnChunks = emittedFns.Count == 0 ? new[] { System.Array.Empty<string>() } : emittedFns.Chunk(FunctionsPerClass).ToArray();
        var names = fnChunks.Select((_, i) => i == 0 ? "DotCcProgram" : $"DotCcProgram{i + 1}").ToArray();
        var source = string.Join("\n\n", fnChunks.Select((chunk, i) =>
            $"static class {names[i]}\n{{\n"
            + IndentBlock(WithAccess(string.Join("\n\n", chunk), "internal"), "    ")
            + "\n}"));
        return (names, source);
    }

    /// <summary><see cref="EmitMode.Translation"/>: the program's own C#, in the order the full shell has it (its
    /// <c>typedef</c> aliases, its functions, its type declarations, its globals), and nothing of the shell.</summary>
    private static string BuildTranslation(string programClasses, string structDecls, string usingAliases, string globals)
    {
        var parts = new List<string>();
        if (usingAliases.Trim().Length > 0) { parts.Add(usingAliases.Trim()); }
        parts.Add(programClasses);
        if (structDecls.Trim().Length > 0) { parts.Add(structDecls.Trim()); }
        if (globals.Trim().Length > 0) { parts.Add("static unsafe class DotCcGlobals\n{\n" + globals + "}"); }
        return string.Join("\n\n", parts) + "\n";
    }

    internal static string BuildShell(
        int mainArity,
        IReadOnlyList<string> emittedFns,
        string structDecls,
        string usingAliases,
        string globals,
        EmitMode emit,
        IReadOnlyList<EmitHelpers.Export> exports,
        bool debugHeap = false,
        string importsClass = "",
        bool importsAreStatic = false,
        bool mainReturnsVoid = false,
        bool mainReturnsErrUnion = false,
        bool mainErrPayloadIsVoid = false,
        bool testMode = false,
        IReadOnlyList<(string Name, string FnName)>? tests = null,
        bool pythonShim = false,
        bool posixPaths = false,
        IReadOnlyList<string>? libraryClasses = null,
        IReadOnlyList<(int Priority, string Name)>? constructors = null)
    {
        // The [[gnu::constructor]] functions run before main, the lower priority first and in
        // definition order among equals. A library has no entry to run them from yet.
        var ctors = (constructors ?? []).OrderBy(c => c.Priority).Select(c => c.Name).ToList();
        if (ctors.Count > 0 && emit == EmitMode.SharedLib)
        {
            throw new CompileException(
                $"dotcc does not yet support: a [[gnu::constructor]] function ('{ctors[0]}') in a shared library");
        }
        var ctorCalls = string.Concat(ctors.Select(n => $"{n}();\n"));
        if (emit == EmitMode.SharedLib)
        {
            return BuildLibraryShell(string.Join("\n\n", emittedFns), structDecls, usingAliases, globals, exports, importsClass, importsAreStatic, pythonShim);
        }
        // Import mode: surface the import table by bare name and splice it into the
        // type-decls section. A GOT (-l) table is bound before main; static [DllImport]
        // stubs bind at the native link, so no startup call. All collapse to nothing
        // when no import was requested, so a normal compile is unchanged.
        var importsClassName = importsAreStatic ? "DotCcStaticImports" : "DotCcImports";
        var importsUsing = importsClass.Length > 0 ? $"\nusing static {importsClassName};" : "";
        var importsBind = (importsClass.Length > 0 && !importsAreStatic) ? "DotCcImports.__BindAll();\n" : "";
        // Embedded DotCC.Libc runtime block — spliced into the heredoc
        // below so the emitted .cs is self-contained even without a
        // <PackageReference Include="DotCC.Libc"> in scope. A program linked
        // against managed libraries (-l with a manifest) uses the runtime they
        // carry instead: one heap, one FILE table and one errno for all of them,
        // and one CBool the library's signatures and the program agree on. Their
        // classes are surfaced by bare name, as the program's own are.
        var runtimeBlock = libraryClasses is { Count: > 0 }
            ? "// ---- the runtime is the linked managed library's"
            : RuntimeBlock(pythonShim);
        var libraryUsings = libraryClasses is { Count: > 0 } libs
            ? "\n" + string.Join("\n", libs.Select(c => $"using static {c};"))
            : "";
        var header = emit == EmitMode.File ? "#:property AllowUnsafeBlocks=true\n\n" : string.Empty;
        // -fsanitize=address: flip the checked debug heap on before any user
        // code (or the embedded runtime) allocates, so every malloc/free
        // downstream carries the header + redzone the checked `free` validates.
        // (DOTCC_DEBUG_HEAP=1 is the equivalent runtime override; see Libc.)
        var debugHeapInit = debugHeap
            ? "Libc.EnableDebugHeap(); // -fsanitize=address: checked malloc/free\n            "
            : string.Empty;
        // -fposix-paths: the POSIX view of Windows paths (GH #254), on before main
        // so argv and the first getcwd already see /c/... (a no-op off Windows).
        // Each argv entry goes through Libc.ViewArgument, which converts one that
        // is an absolute Windows path.
        var posixPathsInit = posixPaths
            ? "Libc.EnablePosixPathView(); // -fposix-paths: /c/... paths on Windows\n            "
            : string.Empty;
        string Arg(string expr) => posixPaths ? $"Libc.ViewArgument({expr})" : expr;
        // User functions live as STATIC METHODS of `DotCcProgram` (not top-level
        // local functions). A top-level local function can't be addressed (`&fn`),
        // stored in a function-pointer table (Lua's `luaL_Reg`), or referenced from
        // several C# contexts (CS8801/CS8422/CS8787) — class methods can. The
        // visitor's `static unsafe` becomes `internal static unsafe` so `using
        // static DotCcProgram;` surfaces them by bare name everywhere (the entry's
        // `main(...)` call, file-scope `&fn` initializers, and inter-function calls).
        // Past FunctionsPerClass the functions continue in DotCcProgram2, DotCcProgram3, ...;
        // C function names are unique in a program, so the imports never collide.
        var (programClassNames, programClasses) = ProgramClasses(emittedFns);
        var programUsings = string.Join("\n", programClassNames.Select(n => $"using static {n};"));
        if (emit == EmitMode.Translation)
        {
            return BuildTranslation(programClasses, structDecls, usingAliases, globals);
        }
        // A `void`-returning main (Zig's `pub fn main() void`; also a non-standard
        // `void main()` in C) can't be `return`ed from the int-typed entry, so it is
        // called for effect and followed by `return 0;`. An int-returning main is
        // returned directly as the process exit code. An ERROR-UNION main (Zig's
        // `pub fn main() !void` / `!u8`, Milestone N part 4) returns an `ErrUnion<…>`:
        // call it into a temp, and (matching real zig) map an error to a non-zero exit
        // (1, with the flat error code reported to stderr — stdout stays clean for the
        // oracle), success to 0 (a void payload) or the integer payload value.
        string Wrap(string call, bool isVoid)
        {
            if (mainReturnsErrUnion)
            {
                var exit = mainErrPayloadIsVoid ? "0" : "(int)__mr.Value";
                return $"var __mr = {call}; if (__mr.IsErr) {{ Console.Error.WriteLine(\"dotcc: error: code \" + __mr.Code); return 1; }} return {exit};";
            }
            return isVoid ? $"{call}; return 0;" : $"return {call};";
        }
        // Test mode (`dotcc zig test`): the entry point IGNORES `main` (a test file usually has none)
        // and instead runs each `test "…" {}` — lowered to an `anyerror!void` `__zigtest_N` method —
        // reporting per-test OK/FAIL and a summary, exit 0 iff all pass. Built here so the shell frame
        // (big-stack worker thread, `using static DotCcProgram;` bare-name calls) is reused verbatim.
        var entry = testMode
            ? BuildTestEntry(tests ?? System.Array.Empty<(string, string)>())
            : mainArity switch
        {
            0 => Wrap("main()", mainReturnsVoid),
            1 => Wrap("main(args.Length)", mainReturnsVoid),
            2 =>
                $$"""
                unsafe
                {
                    // Real C: argv[0] = program path, argv[1..] = user args, argc = total.
                    // .NET hands us only the user args, so synthesize argv[0] from the
                    // running assembly to match clang's vector layout.
                    int argc = args.Length + 1;
                    // +1 for the C-standard NULL sentinel at argv[argc]
                    byte** argv = (byte**)NativeMemory.Alloc((nuint)(argc + 1) * (nuint)sizeof(byte*));
                    static byte* EncodeUtf8Nul(string s)
                    {
                        var bytes = System.Text.Encoding.UTF8.GetBytes(s);
                        var slot = (byte*)NativeMemory.Alloc((nuint)(bytes.Length + 1));
                        for (int k = 0; k < bytes.Length; k++) { slot[k] = bytes[k]; }
                        slot[bytes.Length] = 0;
                        return slot;
                    }
                    argv[0] = EncodeUtf8Nul(
                        {{Arg("System.Environment.ProcessPath ?? System.AppContext.BaseDirectory")}});
                    for (int i = 0; i < args.Length; i++)
                    {
                        argv[i + 1] = EncodeUtf8Nul({{Arg("args[i]")}});
                    }
                    argv[argc] = null; // C standard: argv[argc] == NULL
                    // argv is deliberately NOT freed. In C the argument vector is
                    // owned by the environment and lives for the whole process; a
                    // program may legally mutate it — overwrite an entry with a
                    // pointer it did NOT malloc (chibi's `-q` does `argv[i] =
                    // "-xchibi"`, a string literal) or reassign argv itself — so the
                    // original buffers can't be safely freed by slot here. Reclaiming
                    // it as the process exits would be pointless anyway (the OS does
                    // it); freeing a non-heap pointer aborts the run.
                    {{Wrap("main(argc, argv)", mainReturnsVoid)}}
                }
                """,
            _ => throw new InvalidOperationException(
                $"dotcc: `main` must have 0, 1, or 2 parameters; got {mainArity}."),
        };

        return $$"""
            {{header}}//!dotcc program 1 — generated by dotcc (transpiled C → C#)
            // <auto-generated>
            // Emitted by dotcc from c.lalr.yaml + the input translation units.
            // </auto-generated>
            using System;
            using System.Globalization;
            using System.Numerics;
            using System.IO;
            using System.Runtime.InteropServices;
            using System.Runtime.CompilerServices;
            using System.Threading;
            using System.Collections.Generic;
            using System.Collections.Concurrent;
            using System.Text;
            using System.Net;
            using System.Net.Sockets;
            // ---- DotCC.Libc runtime (embedded source) ----------------
            // The Libc class (declared at file end, spliced in from the
            // ../DotCC.Libc/*.cs sources) holds every libc function +
            // every <math.h>/<tgmath.h> entry — each one with both
            // float and double overloads. Importing it statically here
            // means `sin(x)` / `printf("…")` / `malloc(n)` in user code
            // resolve by bare name to the matching method, and overload
            // resolution picks the right form. That's exactly what
            // <tgmath.h>'s _Generic macros do in real C; we get the
            // same dispatch for free without preprocessor machinery.
            using static Libc;
            // ---- File-scope variables + user functions ----------------
            // C globals are static fields of `DotCcGlobals`; user functions are
            // static methods of `DotCcProgram` (both declared at file end).
            // `using static` on both makes every global + function visible by bare
            // name everywhere — functions call each other and read globals
            // unqualified, the entry below calls `main(...)`, AND a file-scope
            // initializer can take a function's address (`&fn`, the `luaL_Reg`-table
            // idiom) by bare name across the class boundary (using-static surfaces
            // the method group).
            using static DotCcGlobals;
            {{programUsings}}{{importsUsing}}{{libraryUsings}}

            // ---- typedef'd `using` aliases (C# 12+ permits `using unsafe X = Y;`
            //      at file scope, ahead of top-level statements). Empty when no
            //      `typedef` declarations were seen.
            {{usingAliases}}
            // dotcc: run the program entry on a thread with a large stack. A native
            // C program runs on a multi-megabyte stack (Linux defaults to ~8 MB), but
            // .NET's default is ~1 MB — too shallow for deeply-recursive C. Lua's VM,
            // for instance, guards recursion with LUAI_MAXCCALLS (200 nested C calls)
            // on the assumption that 200 frames fit comfortably; on a 1 MB stack the
            // emitted frames overflow at ~100 and crash the runtime before Lua can
            // raise its own catchable "C stack overflow". Reserving 64 MB (virtual
            // address space, not committed memory) restores the native headroom so
            // such programs reach their own recursion guards and fault gracefully.
            {{debugHeapInit}}{{posixPathsInit}}int __dotccExit = 0;
            var __dotccThread = new System.Threading.Thread(
                () => { __dotccExit = __DotCcEntry(); Libc.RunAtExit(); }, 64 * 1024 * 1024);
            __dotccThread.Start();
            __dotccThread.Join();
            return __dotccExit;

            int __DotCcEntry()
            {
            {{importsBind}}{{ctorCalls}}{{entry}}
            }


            // ---- user functions (static methods of DotCcProgram; see the
            //      `using static` note above — class methods, not top-level locals,
            //      so `&fn` / function-pointer tables / cross-context refs work) ----

            {{programClasses}}

            {{importsClass}}
            // ---- type declarations (must come last; C# requires top-level
            //      statements to precede type declarations) ----

            {{structDecls}}

            // C file-scope variables, collected as static fields. Empty
            // class when no globals are declared — harmless but kept for
            // shell-shape stability.
            static unsafe class DotCcGlobals
            {
            {{globals}}}

            {{CondClass}}

            {{runtimeBlock}}
            """;
    }

    /// <summary>
    /// The <c>Cond</c> class every shell declares: C-truthy to C# bool, for a condition whose C#
    /// type has no test written out in place (a <c>_Bool</c>; a scalar or pointer condition is
    /// emitted as <c>x != 0</c> / <c>p != null</c> directly). The overloads live on a static class
    /// because top-level local functions in file-scoped programs can't be overloaded (CS0128).
    /// Overload resolution picks the right form at compile time: bool stays bool; a number
    /// compares against zero; any pointer converts to <c>void*</c> and compares against null.
    /// It is <c>internal</c>, so each assembly has its own.
    /// </summary>
    private const string CondClass = """
        static class Cond
        {
            public static bool B(bool b) => b;
            public static bool B(int x) => x != 0;
            public static bool B(double x) => x != 0;
            public static unsafe bool B(void* p) => p != null;
            // A C scalar of ANY integer/float type is truthy when non-zero;
            // emit one exact overload per lowered numeric type. Without these,
            // a `byte`/`uint`/`long`/`ulong`/… argument (e.g. Lua's `lu_byte`
            // `allowhook`) is convertible to BOTH a built-in numeric overload
            // AND `CBool` (via a one-step user-defined conversion), so the call
            // is ambiguous (CS0121). An exact match beats the user-defined
            // CBool path, so each type resolves unambiguously.
            public static bool B(uint x) => x != 0;
            public static bool B(long x) => x != 0;
            public static bool B(ulong x) => x != 0;
            public static bool B(nint x) => x != 0;
            public static bool B(nuint x) => x != 0;
            public static bool B(sbyte x) => x != 0;
            public static bool B(byte x) => x != 0;
            public static bool B(short x) => x != 0;
            public static bool B(ushort x) => x != 0;
            public static bool B(float x) => x != 0;
            // Relational / logical results lower to CBool (C's int 0/1);
            // unwrap to bool for the conditional position they sit in.
            public static bool B(CBool b) => (int)b != 0;
        }
        """;

    /// <summary>
    /// The shell of a managed library (<see cref="EmitMode.Assembly"/>): the functions, already
    /// given their access by linkage, spread over public classes named
    /// <c>&lt;prefix&gt;_Program</c>, <c>&lt;prefix&gt;_Program2</c>, ... (<see cref="FunctionsPerClass"/>
    /// per class), the objects in the public <c>&lt;prefix&gt;_Globals</c>, the types, and the
    /// runtime, which is public and so the one copy every assembly linked against the library
    /// uses. No entry point. Each of <paramref name="exports"/> also gets an
    /// <c>[UnmanagedCallersOnly]</c> wrapper in <c>&lt;prefix&gt;_Exports</c>, the native entry
    /// point <c>dlsym</c> hands out for it (a C function pointer from <c>dlsym</c> is called with
    /// the C calling convention). A library linked against managed libraries
    /// (<paramref name="libraryClasses"/>, their classes) surfaces them by bare name and uses the
    /// runtime they carry, as <see cref="BuildShell"/> does for a program. Returns the source and
    /// the classes a program surfaces by bare name, the globals class first.
    /// </summary>
    private static (string Program, IReadOnlyList<string> Classes) BuildAssemblyShell(
        string prefix, IReadOnlyList<string> fns, string structDecls, string globals, bool pythonShim,
        IReadOnlyList<EmitHelpers.Export> exports, IReadOnlyList<string> libraryClasses)
    {
        var runtimeBlock = libraryClasses.Count > 0
            ? "// ---- the runtime is the linked managed library's"
            : RuntimeBlock(pythonShim);
        var exportsBlock = new StringBuilder();
        var table = new StringBuilder();
        foreach (var e in exports)
        {
            // The wrapper has a name of its own, so its body's bare call reaches the function
            // (through `using static`), not the wrapper itself.
            var csName = EmitHelpers.Id(e.Name);
            exportsBlock.Append($"    [UnmanagedCallersOnly(EntryPoint = \"{e.Name}\", CallConvs = new[] {{ typeof(CallConvCdecl) }})]\n");
            exportsBlock.Append($"    public static unsafe {e.ReturnType} __export_{e.Name}({e.ParamList}) => {csName}({e.ArgList});\n");
            table.Append($"        (\"{e.Name}\", (nint)({e.PointerType(native: true)})&__export_{e.Name}, (nint)({e.PointerType(native: false)})&{csName}),\n");
        }
        // dlsym's table, which Libc.dlopen reads when a program loads this assembly: each
        // export's C name, its native entry point and the managed function behind it.
        exportsBlock.Append("    public static unsafe (string Name, nint Native, nint Managed)[] __dotcc_exports() =>\n");
        exportsBlock.Append("    [\n").Append(table).Append("    ];\n");
        var fnChunks = fns.Count == 0 ? new[] { System.Array.Empty<string>() } : fns.Chunk(FunctionsPerClass).ToArray();
        var programClassNames = fnChunks.Select((_, i) => i == 0 ? $"{prefix}_Program" : $"{prefix}_Program{i + 1}").ToArray();
        var globalsClass = $"{prefix}_Globals";
        var classes = new List<string> { globalsClass };
        classes.AddRange(programClassNames);
        var usings = string.Join("\n", classes.Concat(libraryClasses).Select(n => $"using static {n};"));
        var programClasses = string.Join("\n\n", fnChunks.Select((chunk, i) =>
            $"public static class {programClassNames[i]}\n{{\n" + IndentBlock(string.Join("\n\n", chunk), "    ") + "\n}"));
        var program = $$"""
            //!dotcc program 1 — generated by dotcc (transpiled C → C#, -shared -fassembly)
            // <auto-generated>
            // Emitted by dotcc from c.lalr.yaml + the input translation units.
            // A managed library: the assemblies linked against it reference its
            // functions, objects, types and runtime.
            // </auto-generated>
            using System;
            using System.Globalization;
            using System.Numerics;
            using System.IO;
            using System.Runtime.InteropServices;
            using System.Runtime.CompilerServices;
            using System.Threading;
            using System.Collections.Generic;
            using System.Collections.Concurrent;
            using System.Text;
            using System.Net;
            using System.Net.Sockets;
            using static Libc;
            {{usings}}

            {{programClasses}}

            {{structDecls}}

            // C file-scope variables, collected as static fields: one object per
            // name for the whole process, whichever assembly takes its address.
            public static unsafe class {{globalsClass}}
            {
            {{globals}}}

            // Native entry points of the functions with external linkage, which
            // dlsym finds by EntryPoint when a program dlopens this assembly.
            public static class {{prefix}}_Exports
            {
            {{exportsBlock}}}

            {{CondClass}}

            {{runtimeBlock}}
            """;
        return (program, classes);
    }

    /// <summary>
    /// Library-mode shell: wraps user functions inside <c>internal static class
    /// DotCcLib</c>, emits a <c>public static class DotCcExports</c> with
    /// <c>[UnmanagedCallersOnly(EntryPoint = "name")]</c> wrappers for every
    /// non-static C function (external linkage). NativeAOT publish turns the
    /// resulting assembly into a real C-callable <c>.dll</c>/<c>.so</c>/<c>.dylib</c>.
    /// </summary>
    private static string BuildLibraryShell(
        string emittedFnList,
        string structDecls,
        string usingAliases,
        string globals,
        IReadOnlyList<EmitHelpers.Export> exports,
        string importsClass = "",
        bool importsAreStatic = false,
        bool pythonShim = false)
    {
        // Import mode in a -shared lib: surface the table by bare name and splice it. A
        // GOT table binds in a static constructor (no entry point here); static [DllImport]
        // stubs bind at the lib's own publish. Empty when no import was requested.
        var importsUsing = importsClass.Length > 0
            ? $"\nusing static {(importsAreStatic ? "DotCcStaticImports" : "DotCcImports")};" : "";
        // Same embedded DotCC.Libc runtime block as exe mode — the
        // library and exe shells share the same set of stdlib functions;
        // only the framing (DotCcLib + DotCcExports vs. top-level
        // statements + `main`) differs.
        var runtimeBlock = RuntimeBlock(pythonShim);
        // Visitor emits user fns as `static unsafe T name(...)` — class-member
        // default is private, which would block DotCcExports from calling
        // them. Promote to `public static unsafe …`. DotCcLib itself is
        // `internal`, so `public` here is effectively assembly-private:
        // external C consumers still only see DotCcExports' attributed methods.
        var publicFns = WithAccess(emittedFnList, "public");
        // Indent the user-function block so it lives correctly inside the class body.
        var indentedFns = IndentBlock(publicFns, "    ");

        // Build the [UnmanagedCallersOnly] wrappers. Skip varargs functions —
        // C# `params` arrays aren't a valid signature for the attribute and
        // can't survive AOT publish.
        var exportsBlock = new StringBuilder();
        foreach (var e in exports)
        {
            if (e.Params.Any(p => p.Type.StartsWith("params ", StringComparison.Ordinal)))
            {
                exportsBlock.Append($"    // dotcc: '{e.Name}' has varargs — not exported (no UnmanagedCallersOnly support).\n");
                continue;
            }
            // EntryPoint keeps the raw C name (the exported C-ABI symbol); the
            // C# wrapper method + the DotCcLib call escape any C#-keyword name.
            var csName = EmitHelpers.Id(e.Name);
            exportsBlock.Append($"    [UnmanagedCallersOnly(EntryPoint = \"{e.Name}\", CallConvs = new[] {{ typeof(CallConvCdecl) }})]\n");
            exportsBlock.Append($"    public static unsafe {e.ReturnType} {csName}({e.ParamList}) => DotCcLib.{csName}({e.ArgList});\n\n");
        }

        return $$"""
            //!dotcc program 1 — generated by dotcc (transpiled C → C#, -shared)
            // <auto-generated>
            // Emitted by dotcc from c.lalr.yaml + the input translation units.
            // Library mode (-shared) — NativeAOT-publishable shared lib with
            // C-ABI exports via [UnmanagedCallersOnly].
            // </auto-generated>
            using System;
            using System.Globalization;
            using System.Numerics;
            using System.IO;
            using System.Runtime.InteropServices;
            using System.Runtime.CompilerServices;
            using System.Threading;
            using System.Collections.Generic;
            using System.Collections.Concurrent;
            using System.Text;
            using System.Net;
            using System.Net.Sockets;
            using static Libc;
            using static DotCcGlobals;
            // A global initializer can name a user function (`&fn` in a C function
            // table), and DotCcGlobals sits outside DotCcLib, so surface DotCcLib by
            // bare name, as the exe shell does with `using static DotCcProgram;`.
            using static DotCcLib;{{importsUsing}}

            // ---- typedef'd `using` aliases (same as exe mode).
            {{usingAliases}}
            // User code lives in an internal class so calls between user fns
            // resolve directly (vs. [UnmanagedCallersOnly] methods which can
            // only be invoked via function pointer from C#). External C
            // consumers reach these through the DotCcExports wrappers below.
            internal static class DotCcLib
            {
            {{indentedFns}}
            }

            // C-ABI exports. Each wrapper trampoline delegates to the matching
            // DotCcLib method; NativeAOT inlines the trampoline at publish.
            public static class DotCcExports
            {
            {{exportsBlock}}}

            {{importsClass}}
            // ---- Type declarations (top-level — same as exe mode). ----
            {{structDecls}}

            // C file-scope variables, collected as static fields (same as
            // exe mode). DotCcLib reaches them via `using static DotCcGlobals;`
            // — adding that import here too so library-mode emits work.
            static unsafe class DotCcGlobals
            {
            {{globals}}}

            {{CondClass}}

            {{runtimeBlock}}
            """;
    }

    /// <summary>
    /// Indent every non-empty line of <paramref name="block"/> by
    /// <paramref name="prefix"/>. Used to drop the user-function string
    /// (emitted at top-level shape) into a class body.
    /// </summary>
    private static string IndentBlock(string block, string prefix)
    {
        if (string.IsNullOrEmpty(block)) { return block; }
        var sb = new StringBuilder(block.Length + 64);
        var first = true;
        foreach (var line in block.Split('\n'))
        {
            if (!first) { sb.Append('\n'); }
            first = false;
            if (line.Length == 0) { continue; }
            sb.Append(prefix).Append(line);
        }
        return sb.ToString();
    }
}
