#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using LALR.CC.LexicalGrammar;

namespace DotCC;

/// <summary>Generated-output templating: the program/library C# shells (entry-point
/// wiring, Cond.B, runtime splice) and the paired csproj. One concern of
/// <see cref="Compiler"/> — entry points live in the main file.</summary>
public static partial class Compiler
{
    /// <summary>
    /// Build the csproj scaffold paired with the non-file-based shell from
    /// <see cref="EmitCSharp"/>. The frontend exe writes both into the output
    /// dir for the default csproj/build modes. When <paramref name="libraryMode"/>
    /// is true, configures <c>NativeLib=Shared</c> + <c>PublishAot=true</c>
    /// so <c>dotnet publish</c> produces a C-callable native shared library
    /// (<c>.dll</c> / <c>.so</c> / <c>.dylib</c>).
    /// </summary>
    public static string BuildGeneratedCsproj(
        bool libraryMode = false, string assemblyName = "dotcc-out", IReadOnlyList<string>? staticArchives = null)
    {
        // Static archives (.a/.lib): link them into the NativeAOT image. <DirectPInvoke>
        // tells ILC to resolve the [DllImport] stubs statically; <NativeLibrary> hands
        // the archive paths to the native linker. Forces PublishAot (static linking is
        // a publish-only operation — there's no CoreCLR static-link step). Empty when
        // no archive inputs were given.
        var staticItems = "";
        if (staticArchives is { Count: > 0 })
        {
            var sb = new StringBuilder();
            sb.Append("  <PropertyGroup>\n    <PublishAot>true</PublishAot>\n  </PropertyGroup>\n");
            sb.Append("  <ItemGroup>\n");
            foreach (var name in staticArchives.Select(StaticArchiveDllName).Distinct(StringComparer.Ordinal))
            {
                sb.Append($"    <DirectPInvoke Include=\"{name}\" />\n");
            }
            foreach (var path in staticArchives)
            {
                sb.Append($"    <NativeLibrary Include=\"{path.Replace('\\', '/')}\" />\n");
            }
            sb.Append("  </ItemGroup>\n");
            staticItems = sb.ToString();
        }

        if (libraryMode)
        {
            return $"""
                <Project Sdk="Microsoft.NET.Sdk">
                  <!-- Generated by dotcc (library mode, -shared). -->
                  <PropertyGroup>
                    <OutputType>Library</OutputType>
                    <TargetFramework>net10.0</TargetFramework>
                    <RootNamespace>DotCCGenerated</RootNamespace>
                    <AssemblyName>{assemblyName}</AssemblyName>
                    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
                    <Nullable>disable</Nullable>
                    <!-- NativeAOT shared-library knobs. Producing the actual
                         .so/.dll/.dylib requires `dotnet publish`. -->
                    <PublishAot>true</PublishAot>
                    <NativeLib>Shared</NativeLib>
                    <IsTrimmable>true</IsTrimmable>
                  </PropertyGroup>
                {staticItems}</Project>
                """;
        }
        return $"""
            <Project Sdk="Microsoft.NET.Sdk">
              <!-- Generated by dotcc. -->
              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net10.0</TargetFramework>
                <RootNamespace>DotCCGenerated</RootNamespace>
                <AssemblyName>{assemblyName}</AssemblyName>
                <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
                <Nullable>disable</Nullable>
              </PropertyGroup>
            {staticItems}</Project>
            """;
    }

    internal static string BuildShell(
        int mainArity,
        string emittedFnList,
        string structDecls,
        string usingAliases,
        string globals,
        EmitMode emit,
        IReadOnlyList<EmitHelpers.Export> exports,
        bool debugHeap = false,
        string importsClass = "",
        bool importsAreStatic = false,
        bool mainReturnsVoid = false,
        bool mainReturnsErrUnion = false,
        bool mainErrPayloadIsVoid = false)
    {
        if (emit == EmitMode.SharedLib)
        {
            return BuildLibraryShell(emittedFnList, structDecls, usingAliases, globals, exports, importsClass, importsAreStatic);
        }
        // Import mode: surface the import table by bare name and splice it into the
        // type-decls section. A GOT (-l) table is bound before main; static [DllImport]
        // stubs bind at the native link, so no startup call. All collapse to nothing
        // when no import was requested, so a normal compile is unchanged.
        var importsClassName = importsAreStatic ? "DotCcStaticImports" : "DotCcImports";
        var importsUsing = importsClass.Length > 0 ? $"\nusing static {importsClassName};" : "";
        var importsBind = (importsClass.Length > 0 && !importsAreStatic) ? "DotCcImports.__BindAll();\n" : "";
        // Embedded DotCC.Libc runtime block — spliced into the heredoc
        // below so the emitted .cs is self-contained even without a
        // <PackageReference Include="DotCC.Libc"> in scope.
        var runtimeBlock = _runtimeBlock.Value;
        var header = emit == EmitMode.File ? "#:property AllowUnsafeBlocks=true\n\n" : string.Empty;
        // -fsanitize=address: flip the checked debug heap on before any user
        // code (or the embedded runtime) allocates, so every malloc/free
        // downstream carries the header + redzone the checked `free` validates.
        // (DOTCC_DEBUG_HEAP=1 is the equivalent runtime override; see Libc.)
        var debugHeapInit = debugHeap
            ? "Libc.EnableDebugHeap(); // -fsanitize=address: checked malloc/free\n            "
            : string.Empty;
        // User functions live as STATIC METHODS of `DotCcProgram` (not top-level
        // local functions). A top-level local function can't be addressed (`&fn`),
        // stored in a function-pointer table (Lua's `luaL_Reg`), or referenced from
        // several C# contexts (CS8801/CS8422/CS8787) — class methods can. The
        // visitor's `static unsafe` becomes `internal static unsafe` so `using
        // static DotCcProgram;` surfaces them by bare name everywhere (the entry's
        // `main(...)` call, file-scope `&fn` initializers, and inter-function calls).
        var indentedFns = IndentBlock(
            emittedFnList.Replace("static unsafe ", "internal static unsafe "), "    ");
        // A `void`-returning main (Zig's `pub fn main() void`; also a non-standard
        // `void main()` in C) can't be `return`ed from the int-typed entry, so it is
        // called for effect and followed by `return 0;`. An int-returning main is
        // returned directly as the process exit code. An ERROR-UNION main (Zig's
        // `pub fn main() !void` / `!u8`, Milestone N part 4) returns an `ErrUnion<…>`:
        // call it into a temp, and (matching real zig) map an error to a non-zero exit
        // (1, with the flat error code reported to stderr — stdout stays clean for the
        // oracle), success to 0 (a void payload) or the integer payload value.
        string Wrap(string call, bool isVoid)
        {
            if (mainReturnsErrUnion)
            {
                var exit = mainErrPayloadIsVoid ? "0" : "(int)__mr.Value";
                return $"var __mr = {call}; if (__mr.IsErr) {{ Console.Error.WriteLine(\"dotcc: error: code \" + __mr.Code); return 1; }} return {exit};";
            }
            return isVoid ? $"{call}; return 0;" : $"return {call};";
        }
        var entry = mainArity switch
        {
            0 => Wrap("main()", mainReturnsVoid),
            1 => Wrap("main(args.Length)", mainReturnsVoid),
            2 =>
                $$"""
                unsafe
                {
                    // Real C: argv[0] = program path, argv[1..] = user args, argc = total.
                    // .NET hands us only the user args, so synthesize argv[0] from the
                    // running assembly to match clang's vector layout.
                    int argc = args.Length + 1;
                    // +1 for the C-standard NULL sentinel at argv[argc]
                    byte** argv = (byte**)NativeMemory.Alloc((nuint)(argc + 1) * (nuint)sizeof(byte*));
                    static byte* EncodeUtf8Nul(string s)
                    {
                        var bytes = System.Text.Encoding.UTF8.GetBytes(s);
                        var slot = (byte*)NativeMemory.Alloc((nuint)(bytes.Length + 1));
                        for (int k = 0; k < bytes.Length; k++) { slot[k] = bytes[k]; }
                        slot[bytes.Length] = 0;
                        return slot;
                    }
                    argv[0] = EncodeUtf8Nul(
                        System.Environment.ProcessPath ?? System.AppContext.BaseDirectory);
                    for (int i = 0; i < args.Length; i++)
                    {
                        argv[i + 1] = EncodeUtf8Nul(args[i]);
                    }
                    argv[argc] = null; // C standard: argv[argc] == NULL
                    // argv is deliberately NOT freed. In C the argument vector is
                    // owned by the environment and lives for the whole process; a
                    // program may legally mutate it — overwrite an entry with a
                    // pointer it did NOT malloc (chibi's `-q` does `argv[i] =
                    // "-xchibi"`, a string literal) or reassign argv itself — so the
                    // original buffers can't be safely freed by slot here. Reclaiming
                    // it as the process exits would be pointless anyway (the OS does
                    // it); freeing a non-heap pointer aborts the run.
                    {{Wrap("main(argc, argv)", mainReturnsVoid)}}
                }
                """,
            _ => throw new InvalidOperationException(
                $"dotcc: `main` must have 0, 1, or 2 parameters; got {mainArity}."),
        };

        return $$"""
            {{header}}//!dotcc program 1 — generated by dotcc (transpiled C → C#)
            // <auto-generated>
            // Emitted by dotcc from c.lalr.yaml + the input translation units.
            // </auto-generated>
            using System;
            using System.Globalization;
            using System.Numerics;
            using System.IO;
            using System.Runtime.InteropServices;
            using System.Runtime.CompilerServices;
            using System.Threading;
            using System.Collections.Generic;
            using System.Collections.Concurrent;
            using System.Text;
            using System.Net;
            using System.Net.Sockets;
            // ---- DotCC.Libc runtime (embedded source) ----------------
            // The Libc class (declared at file end, spliced in from the
            // ../DotCC.Libc/*.cs sources) holds every libc function +
            // every <math.h>/<tgmath.h> entry — each one with both
            // float and double overloads. Importing it statically here
            // means `sin(x)` / `printf("…")` / `malloc(n)` in user code
            // resolve by bare name to the matching method, and overload
            // resolution picks the right form. That's exactly what
            // <tgmath.h>'s _Generic macros do in real C; we get the
            // same dispatch for free without preprocessor machinery.
            using static Libc;
            // ---- File-scope variables + user functions ----------------
            // C globals are static fields of `DotCcGlobals`; user functions are
            // static methods of `DotCcProgram` (both declared at file end).
            // `using static` on both makes every global + function visible by bare
            // name everywhere — functions call each other and read globals
            // unqualified, the entry below calls `main(...)`, AND a file-scope
            // initializer can take a function's address (`&fn`, the `luaL_Reg`-table
            // idiom) by bare name across the class boundary (using-static surfaces
            // the method group).
            using static DotCcGlobals;
            using static DotCcProgram;{{importsUsing}}

            // ---- typedef'd `using` aliases (C# 12+ permits `using unsafe X = Y;`
            //      at file scope, ahead of top-level statements). Empty when no
            //      `typedef` declarations were seen.
            {{usingAliases}}
            // dotcc: run the program entry on a thread with a large stack. A native
            // C program runs on a multi-megabyte stack (Linux defaults to ~8 MB), but
            // .NET's default is ~1 MB — too shallow for deeply-recursive C. Lua's VM,
            // for instance, guards recursion with LUAI_MAXCCALLS (200 nested C calls)
            // on the assumption that 200 frames fit comfortably; on a 1 MB stack the
            // emitted frames overflow at ~100 and crash the runtime before Lua can
            // raise its own catchable "C stack overflow". Reserving 64 MB (virtual
            // address space, not committed memory) restores the native headroom so
            // such programs reach their own recursion guards and fault gracefully.
            {{debugHeapInit}}int __dotccExit = 0;
            var __dotccThread = new System.Threading.Thread(
                () => { __dotccExit = __DotCcEntry(); }, 64 * 1024 * 1024);
            __dotccThread.Start();
            __dotccThread.Join();
            return __dotccExit;

            int __DotCcEntry()
            {
            {{importsBind}}{{entry}}
            }


            // ---- user functions (static methods of DotCcProgram; see the
            //      `using static` note above — class methods, not top-level locals,
            //      so `&fn` / function-pointer tables / cross-context refs work) ----

            static unsafe class DotCcProgram
            {
            {{indentedFns}}
            }

            {{importsClass}}
            // ---- type declarations (must come last; C# requires top-level
            //      statements to precede type declarations) ----

            {{structDecls}}

            // C file-scope variables, collected as static fields. Empty
            // class when no globals are declared — harmless but kept for
            // shell-shape stability.
            static unsafe class DotCcGlobals
            {
            {{globals}}}

            // C-truthy → C# bool. The visitor wraps every conditional context
            // (`if`/`while`/`for`-cond) with `Cond.B(...)` so int- and
            // pointer-valued conditions (`while (1)`, `if (p)`, `while (--n)`)
            // typecheck. Overloads live on a static class because top-level
            // local functions in file-scoped programs can't be overloaded
            // (CS0128). Overload resolution picks the right form at compile
            // time: bool stays bool; int/double compare against zero; any
            // pointer implicitly converts to void* and compares against null.
            static class Cond
            {
                public static bool B(bool b) => b;
                public static bool B(int x) => x != 0;
                public static bool B(double x) => x != 0;
                public static unsafe bool B(void* p) => p != null;
                // A C scalar of ANY integer/float type is truthy when non-zero;
                // emit one exact overload per lowered numeric type. Without these,
                // a `byte`/`uint`/`long`/`ulong`/… argument (e.g. Lua's `lu_byte`
                // `allowhook`) is convertible to BOTH a built-in numeric overload
                // AND `CBool` (via a one-step user-defined conversion), so the call
                // is ambiguous (CS0121). An exact match beats the user-defined
                // CBool path, so each type resolves unambiguously.
                public static bool B(uint x) => x != 0;
                public static bool B(long x) => x != 0;
                public static bool B(ulong x) => x != 0;
                public static bool B(nint x) => x != 0;
                public static bool B(nuint x) => x != 0;
                public static bool B(sbyte x) => x != 0;
                public static bool B(byte x) => x != 0;
                public static bool B(short x) => x != 0;
                public static bool B(ushort x) => x != 0;
                public static bool B(float x) => x != 0;
                // Relational / logical results lower to CBool (C's int 0/1);
                // unwrap to bool for the conditional position they sit in.
                public static bool B(CBool b) => (int)b != 0;
            }

            {{runtimeBlock}}
            """;
    }

    /// <summary>
    /// Library-mode shell: wraps user functions inside <c>internal static class
    /// DotCcLib</c>, emits a <c>public static class DotCcExports</c> with
    /// <c>[UnmanagedCallersOnly(EntryPoint = "name")]</c> wrappers for every
    /// non-static C function (external linkage). NativeAOT publish turns the
    /// resulting assembly into a real C-callable <c>.dll</c>/<c>.so</c>/<c>.dylib</c>.
    /// </summary>
    private static string BuildLibraryShell(
        string emittedFnList,
        string structDecls,
        string usingAliases,
        string globals,
        IReadOnlyList<EmitHelpers.Export> exports,
        string importsClass = "",
        bool importsAreStatic = false)
    {
        // Import mode in a -shared lib: surface the table by bare name and splice it. A
        // GOT table binds in a static constructor (no entry point here); static [DllImport]
        // stubs bind at the lib's own publish. Empty when no import was requested.
        var importsUsing = importsClass.Length > 0
            ? $"\nusing static {(importsAreStatic ? "DotCcStaticImports" : "DotCcImports")};" : "";
        // Same embedded DotCC.Libc runtime block as exe mode — the
        // library and exe shells share the same set of stdlib functions;
        // only the framing (DotCcLib + DotCcExports vs. top-level
        // statements + `main`) differs.
        var runtimeBlock = _runtimeBlock.Value;
        // Visitor emits user fns as `static unsafe T name(...)` — class-member
        // default is private, which would block DotCcExports from calling
        // them. Promote to `public static unsafe …`. DotCcLib itself is
        // `internal`, so `public` here is effectively assembly-private:
        // external C consumers still only see DotCcExports' attributed methods.
        var publicFns = emittedFnList.Replace("static unsafe ", "public static unsafe ");
        // Indent the user-function block so it lives correctly inside the class body.
        var indentedFns = IndentBlock(publicFns, "    ");

        // Build the [UnmanagedCallersOnly] wrappers. Skip varargs functions —
        // C# `params` arrays aren't a valid signature for the attribute and
        // can't survive AOT publish.
        var exportsBlock = new StringBuilder();
        foreach (var e in exports)
        {
            if (e.Params.Contains("params VaArg[]", StringComparison.Ordinal))
            {
                exportsBlock.Append($"    // dotcc: '{e.Name}' has varargs — not exported (no UnmanagedCallersOnly support).\n");
                continue;
            }
            var argNames = ExtractArgNames(e.Params);
            // EntryPoint keeps the raw C name (the exported C-ABI symbol); the
            // C# wrapper method + the DotCcLib call escape any C#-keyword name.
            var csName = EmitHelpers.Id(e.Name);
            exportsBlock.Append($"    [UnmanagedCallersOnly(EntryPoint = \"{e.Name}\", CallConvs = new[] {{ typeof(CallConvCdecl) }})]\n");
            exportsBlock.Append($"    public static unsafe {e.ReturnType} {csName}({e.Params}) => DotCcLib.{csName}({argNames});\n\n");
        }

        return $$"""
            //!dotcc program 1 — generated by dotcc (transpiled C → C#, -shared)
            // <auto-generated>
            // Emitted by dotcc from c.lalr.yaml + the input translation units.
            // Library mode (-shared) — NativeAOT-publishable shared lib with
            // C-ABI exports via [UnmanagedCallersOnly].
            // </auto-generated>
            using System;
            using System.Globalization;
            using System.Numerics;
            using System.IO;
            using System.Runtime.InteropServices;
            using System.Runtime.CompilerServices;
            using System.Threading;
            using System.Collections.Generic;
            using System.Collections.Concurrent;
            using System.Text;
            using System.Net;
            using System.Net.Sockets;
            using static Libc;
            using static DotCcGlobals;{{importsUsing}}

            // ---- typedef'd `using` aliases (same as exe mode).
            {{usingAliases}}
            // User code lives in an internal class so calls between user fns
            // resolve directly (vs. [UnmanagedCallersOnly] methods which can
            // only be invoked via function pointer from C#). External C
            // consumers reach these through the DotCcExports wrappers below.
            internal static class DotCcLib
            {
            {{indentedFns}}
            }

            // C-ABI exports. Each wrapper trampoline delegates to the matching
            // DotCcLib method; NativeAOT inlines the trampoline at publish.
            public static class DotCcExports
            {
            {{exportsBlock}}}

            {{importsClass}}
            // ---- Type declarations (top-level — same as exe mode). ----
            {{structDecls}}

            // C file-scope variables, collected as static fields (same as
            // exe mode). DotCcLib reaches them via `using static DotCcGlobals;`
            // — adding that import here too so library-mode emits work.
            static unsafe class DotCcGlobals
            {
            {{globals}}}

            // C-truthy → C# bool. Same set of overloads as exe mode.
            static class Cond
            {
                public static bool B(bool b) => b;
                public static bool B(int x) => x != 0;
                public static bool B(double x) => x != 0;
                public static unsafe bool B(void* p) => p != null;
                // A C scalar of ANY integer/float type is truthy when non-zero;
                // emit one exact overload per lowered numeric type. Without these,
                // a `byte`/`uint`/`long`/`ulong`/… argument (e.g. Lua's `lu_byte`
                // `allowhook`) is convertible to BOTH a built-in numeric overload
                // AND `CBool` (via a one-step user-defined conversion), so the call
                // is ambiguous (CS0121). An exact match beats the user-defined
                // CBool path, so each type resolves unambiguously.
                public static bool B(uint x) => x != 0;
                public static bool B(long x) => x != 0;
                public static bool B(ulong x) => x != 0;
                public static bool B(nint x) => x != 0;
                public static bool B(nuint x) => x != 0;
                public static bool B(sbyte x) => x != 0;
                public static bool B(byte x) => x != 0;
                public static bool B(short x) => x != 0;
                public static bool B(ushort x) => x != 0;
                public static bool B(float x) => x != 0;
                // Relational / logical results lower to CBool (C's int 0/1);
                // unwrap to bool for the conditional position they sit in.
                public static bool B(CBool b) => (int)b != 0;
            }

            {{runtimeBlock}}
            """;
    }

    /// <summary>
    /// Indent every non-empty line of <paramref name="block"/> by
    /// <paramref name="prefix"/>. Used to drop the user-function string
    /// (emitted at top-level shape) into a class body.
    /// </summary>
    private static string IndentBlock(string block, string prefix)
    {
        if (string.IsNullOrEmpty(block)) { return block; }
        var sb = new StringBuilder(block.Length + 64);
        var first = true;
        foreach (var line in block.Split('\n'))
        {
            if (!first) { sb.Append('\n'); }
            first = false;
            if (line.Length == 0) { continue; }
            sb.Append(prefix).Append(line);
        }
        return sb.ToString();
    }

    /// <summary>
    /// Extract bare argument names from a C# parameter list like
    /// <c>"int* arr, int n, Comparator cmp"</c> → <c>"arr, n, cmp"</c>.
    /// Used to generate <c>[UnmanagedCallersOnly]</c> wrapper call sites
    /// that delegate to the underlying impl with matching argument order.
    /// </summary>
    private static string ExtractArgNames(string paramList)
    {
        if (string.IsNullOrEmpty(paramList)) { return string.Empty; }
        var parts = paramList.Split(", ");
        var sb = new StringBuilder();
        for (var i = 0; i < parts.Length; i++)
        {
            var p = parts[i];
            var sp = p.LastIndexOf(' ');
            if (i > 0) { sb.Append(", "); }
            sb.Append(sp < 0 ? p : p[(sp + 1)..]);
        }
        return sb.ToString();
    }
}
