#!/usr/bin/env python
"""Regenerate DotCC.Lib/Ir/ParseTreeIdentityVisitor.cs from the generated
C.IVisitor<T> surface. Run after the grammar (c.lalr.yaml) changes the set of
AST records, then rebuild. Usage: python scripts/gen-identity-visitor.py
(run from the repo root; requires a prior build so the generated file exists)."""
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
GEN = ROOT / ("DotCC.Lib/obj/generated/LALR.CC.SourceGenerators/"
              "LALR.CC.SourceGenerators.GrammarSourceGenerator/C.Visitor.g.cs")
OUT = ROOT / "DotCC.Lib/Ir/ParseTreeIdentityVisitor.cs"

src = GEN.read_text()
m = re.search(r"interface IVisitor<out T>\s*\{(.*?)\n    \}", src, re.S)
if not m:
    raise SystemExit("could not find IVisitor<out T> in " + str(GEN))
names = re.findall(r"T Visit\((\w+) node\);", m.group(1))

lines = [
    "#nullable enable",
    "",
    "namespace DotCC.Ir;",
    "",
    "/// <summary>",
    "/// Identity visitor over the generated LALR parse tree. Every <c>Visit</c>",
    "/// overload returns its own <c>C.&lt;Record&gt;</c> node unchanged, so when this",
    "/// visitor drives the parser, each reduced <c>Item.Content</c> holds the raw",
    "/// grammar record (and terminal children stay raw lexeme strings). That lets",
    "/// <see cref=\"IrBuilder\"/> walk the concrete parse tree TOP-DOWN with full",
    "/// scope/type context. Generated by scripts/gen-identity-visitor.py — rerun it",
    "/// if the grammar surface changes.",
    "/// </summary>",
    "internal sealed class ParseTreeIdentityVisitor : C.IVisitor<object>",
    "{",
    "    /// <summary>Shared singleton — the visitor is stateless.</summary>",
    "    public static readonly ParseTreeIdentityVisitor Instance = new();",
    "",
]
lines += [f"    public object Visit(C.{n} node) => node;" for n in names]
lines.append("}")
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {len(names)} Visit methods to {OUT.relative_to(ROOT)}")
